# ServerBalancer configuration
# Лобанов Р.Е. — Итоговый проект, Вариант 7

lambda_total: 150.0      # суммарный поток запросов (req/s)
rho_max: 0.90            # максимально допустимая загрузка сервера

servers:
  - id: 0
    mu: 100.0             # сервер 1: высокопроизводительный (req/s)
  - id: 1
    mu: 80.0              # сервер 2: средний
  - id: 2
    mu: 60.0              # сервер 3: слабый

simulation_duration: 3000.0   # длительность SimPy-симуляции (сек. модельного времени)
